### ISSUE TITLE
Closing tag '[/]' at position 73 has nothing to close

### ISSUE THREAD

**Issue by w4h4z** [oppsec/Pinkerton#1] opened 2022-07-17 10:46 UTC
Hello, I try this tool but get error when first trying.
$ python3 main.py -u https://example.com

Traceback (most recent call last):
  File "main.py", line 15, in <module>
    check_host(args)
  File "/root/pinkerton/src/pinkerton/main.py", line 25, in check_host
    print(f"[bold white on green]> Connected sucessfully with {url}[/] [/]")
  File "/usr/local/lib/python3.7/dist-packages/rich/__init__.py", line 73, in print
    return write_console.print(*objects, sep=sep, end=end)
  File "/usr/local/lib/python3.7/dist-packages/rich/console.py", line 1643, in print
    highlight=highlight,
  File "/usr/local/lib/python3.7/dist-packages/rich/console.py", line 1501, in _collect_renderables
    renderable, emoji=emoji, markup=markup, highlighter=_highlighter
  File "/usr/local/lib/python3.7/dist-packages/rich/console.py", line 1396, in render_str
    emoji_variant=self._emoji_variant,
  File "/usr/local/lib/python3.7/dist-packages/rich/markup.py", line 170, in render
    ) from None
rich.errors.MarkupError: closing tag '[/]' at position 73 has nothing to close

**Comment by srand2** [comment] 2022-07-17 15:07
I have the same issue

**Comment by diwsec** [comment] 2022-07-17 17:04
same issue

**Comment by tamimhasan404** [comment] 2022-07-17 23:31
Sadly same issue😥

**Comment by r3l1c7** [comment] 2022-07-18 00:22
same

**Comment by S7Sh4rk** [comment] 2022-07-18 05:40
Same issue

**Comment by kavishgr** [comment] 2022-07-18 06:05
yep same issue

**Comment by dimazarno** [comment] 2022-07-18 11:08
just remove last [/] at the line 25 on src/pinkerton/main.py

from:

print(f"[bold white on green]> Connected sucessfully with {url}[/] [/]")

into:

print(f"[bold white on green]> Connected sucessfully with {url}[/]")

**Comment by oppsec** [comment] 2022-07-18 16:58
I have now committed a fix for this issue, can you check if it's working? @w4h4z etc...

Sorry for making you wait so long, I arrived to my home today only

**Comment by oppsec** [comment] 2022-07-18 17:20
> Can confirm making the change recommended by @dimazarno worked. Thanks!

Thanks for confirming @IronLion267, I'll close this issue because the problem is already fixed. Thanks to everyone too!

Best regards,
oppsec.

**Closed as completed** 2022-07-18 17:21 UTC
Labels: bug, good first issue
